### ISSUE TITLE
Administration and Registration Service not starting

### ISSUE THREAD

**Issue by Phil91** [eclipse-tractusx/portal-backend#1144]
### Current Behavior
When trying to start the administration service the application fails during the startup process

### Expected Behavior
The administration service should start up without any errors

### Steps To Reproduce
Checkout the code and try to startup the administration service.

### Additional information
The error occurs due to a missing registration for `IIdentityProviderProvisioningService`

This bug was introduced with #1010

**Comment by evegufy** [comment]
@Phil91 I still see the same issue for the registration service:

`
{"Timestamp":"2024-11-12T19:27:21.0447568+00:00","Level":"Fatal","MessageTemplate":"Start failed due to unhandled exception","RenderedMessage":"Start failed due to unhandled exception","Exception":"System.AggregateException: Some services are not able to be constructed (Error while validating the service descriptor 'ServiceType: Org.Eclipse.TractusX.Portal.Backend.Registration.Service.BusinessLogic.IRegistrationBusinessLogic Lifetime: Transient ImplementationType: Org.Eclipse.TractusX.Portal.Backend.Registration.Service.BusinessLogic.RegistrationBusinessLogic': Unable to resolve service for type 'Org.Eclipse.TractusX.Portal.Backend.Provisioning.Library.Service.IIdentityProviderProvisioningService' while attempting to activate 'Org.Eclipse.TractusX.Portal.Backend.Registration.Service.BusinessLogic.RegistrationBusinessLogic'.)
...
`

**Comment by MaximilianHauer** [comment]
@evegufy  would you retest it ?

**Comment by evegufy** [comment]
I retested already last week
