### ISSUE TITLE
App subscription trigger provider is not Working 

### ISSUE THREAD

**Issue by gopalreddy-bmw** [eclipse-tractusx/portal-backend#1169]
**Current Behaviour**
App subscription trigger provider is not Working.

**Screenshot**
![image](https://github.com/user-attachments/assets/a9f9a15c-4606-43b2-ac9e-e3d62fbd2f9b)

**Expected Behaviour**
App subscription trigger provider should be Work.

**Steps To Reproduce**
1.Login to https://portal.int.catena-x.net/appSubscription
2.Subcribe any app 
3. Provider should approved the app

**Comment by evegufy** [comment]
Hi @gopalreddy-bmw could you please better describe what the expected behavior is or what doesn't work?
I just tested the functionality and it worked fine.
Please be aware that in your test company somebody set an (invalid) auto-setup url:
<img width="739" alt="image" src="https://github.com/user-attachments/assets/e37ead18-9e6f-4c20-86fa-e36698c7a462">
So the subsciptions will remain in pending as long as there isn't valid auto setup url or somebody remove that url again, see https://github.com/eclipse-tractusx/portal-assets/blob/main/docs/admin/Interface%20Contracts/Offer-Autosetup.md

**Comment by Phil91** [comment]
created the issue: https://github.com/eclipse-tractusx/portal-backend/issues/1175

@evegufy @gopalreddy-bmw fyi, going to close this issue
