### ISSUE TITLE
TRG 7.05 Legal information for distributions

### ISSUE THREAD

**Issue by carslen** [eclipse-tractusx/portal-backend#360]
https://github.com/eclipse-tractusx/portal-backend/blob/95a0465132f4ad9c1f773778510ebef4852a6198/docker/Dockerfile-administration-service#L24

Please copy legal information for distributions next to your app in `/app` folder. This will avoid misunderstandings about what is covered under which license.

This applies to all Dockerfiles in repository.

**Comment by carslen** [comment]
Thank's for clarification. Does this apply to all docker images? If yes, then I'll close this issue.

In build stage no legal information are required. To save Docker image layers, you could remove this from publish container, which is used to build.

**Comment by evegufy** [comment]
Yes, this does apply to all docker images.
And 

> Thank's for clarification. Does this apply to all docker images? If yes, then I'll close this issue.
> 

Yes, this does apply to all docker images.

> In build stage no legal information are required. To save Docker image layers, you could remove this from publish container, which is used to build.

They are required, the apps need those files to be available in order to build due to [CopyToOutputDirectory](https://github.com/eclipse-tractusx/portal-backend/blob/95a0465132f4ad9c1f773778510ebef4852a6198/src/administration/Administration.Service/Administration.Service.csproj#L66).
