### ISSUE TITLE
Enhance GET /api/apps/subscribed/subscription-status Endpoint with Filter for Subscription Status

### ISSUE THREAD

**Issue by jjeroch** [eclipse-tractusx/portal-backend#592]
#### Description:
The current implementation of the GET `/api/apps/subscribed/subscription-status` endpoint retrieves subscription status information for all subscribed apps. To provide more flexibility and allow clients to filter the results based on the subscription status, we need to enhance the endpoint by adding a filter parameter for the subscription status. 
The filter parameter should support:
- "All"
- "Active"
- "Pending"

#### Tasks:
1. Update the endpoint's request model to include a new query parameter named `status` to filter the subscription status
2. Modify the logic of the endpoint to filter the subscribed apps based on the app subscription `status` parameter.
   - If the `status` parameter is not provided, return all subscribed apps without any filtering.
   - If the `status` parameter is provided, filter the subscribed apps based on the specified status (Either "ACTIVE" or "PENDING")
3. Update the API documentation (Swagger) to reflect the changes in the endpoint and provide details about the new filter parameter.
4. Write unit tests to ensure the correctness of the updated logic and the proper handling of the filter parameter.
5. Perform integration testing to verify that the endpoint returns the expected results when using the filter parameter for different subscription status values.

<br>

Linked tickets:  https://github.com/eclipse-tractusx/portal-frontend/issues/669

**Comment by Phil91** [comment]
@jjeroch I've added the filter to the endpoint `GET: /api/services/subscribed/subscription-status` as well, because we use the same logic in the background. Since it's an optional parameter it shouldn't be any problem and we don't have to use it if we don't want to, but could use it if wanted. So imo only benefits :)

Additionally in the issue it's mentioned to filter for `All`, `Active`and `Pending` in the backend the enum consists out of the following values: `Active`,`Pending` & `Inactive` since the `All` can be achieved by not setting the query param I'd suggest to just use the enum we're using for our database values as well, is that okay?

@MaximilianHauer fyi

**Comment by MaximilianHauer** [comment]
@Phil91 we would need to adjust the parameter to be  `?status` from `?statusId` 

@lavanya-bmw  then it should work.
