### ISSUE TITLE
Error when trying to reject a registration request as an administrator

### ISSUE THREAD

**Issue by danakoch23** [eclipse-tractusx/portal-backend#724]
**Error message:** `"errorId": "b3762e59-f0fe-4c49-9b88-f3e6be3cbdfd", "details": []`

## Problem Description
When attempting to reject a registration request as an administrator, an error occurs. The system returns an error message with the `errorId` "b3762e59-f0fe-4c49-9b88-f3e6be3cbdfd" and no additional details.

## Steps to Reproduce
1. Log in as an administrator
2. Select a registration request to reject
3. Initiate the rejection process
4. Receive the error message with the `errorId` "b3762e59-f0fe-4c49-9b88-f3e6be3cbdfd"

## Expected Behavior
The registration request should be able to be rejected without any errors, and the error message with the `errorId` "b3762e59-f0fe-4c49-9b88-f3e6be3cbdfd" should not appear.

- User Role: Administrator

**Comment by Phil91** [comment]
Double checked the process, it's working. @jjeroch we might consider to create a process for the rejection as well since all keycloak calls are handled in the same request, which is very error prone due to the fact that one failing keycloak call will lead to the issue that the rejection can't be handled completely and is stuck and manual intervention is needed - which was the case with this issue
