### ISSUE TITLE
[E2E 24.08] App provider autosetup | App not activated in marketplace

### ISSUE THREAD

**Issue by ciprianherciu** [eclipse-tractusx/portal-backend#856]
### Current Behavior
After a subscription and a successful run of the MSO we try to open the application from the Portal.
First problem is that the Application does not appear as active in the App Marketplace
<img width="991" alt="Screenshot 2024-07-22 at 1 16 59 PM" src="https://github.com/user-attachments/assets/96a0a51d-c6f8-4f8d-a960-b71cb68f1ebc">

While trying still to open the client disabled 
<img width="975" alt="Screenshot 2024-07-22 at 12 46 06 PM" src="https://github.com/user-attachments/assets/1fa6829d-5936-46c1-a594-
<img width="975" alt="Screenshot 2024-07-22 at 1 14 45 PM" src="https://github.com/user-attachments/assets/720d9d76-c252-480d-83f0-c8026667d4d5">
c838b69a772b">

Application is not activated in the App Marketplace

### Expected Behavior
Application should be activated in the App Marketplace 

### Steps To Reproduce
1. Subscribe to Managed SDE
2. After the successful deployment try to open the application
3. Application appears as inactive in App Marketplace
4. While trying to access the client it appears as Client Disabled

**Comment by evegufy** [comment]
@ciprianherciu If you requested a technical user for Identity Wallet Management, the technical user creation takes a couple of minutes, and the app subscription is shown as pending for that time.
Could you check if the app subscription is now in state “Configure”?

**Comment by evegufy** [comment]
Issue is still under validation it's already clear that it's restricted to app provider autosetup usage.

**Comment by evegufy** [comment]
The app subscriptions are currently in pending state, current state of process_steps table for the process:
<img width="269" alt="image" src="https://github.com/user-attachments/assets/cffbda1e-9170-4237-903b-e6cb877a7b70">

It appears that their is some issue in the context of the app provider call back to activate the subscription
https://github.com/eclipse-tractusx/portal-assets/blob/v2.0.0/docs/user/04.%20App(s)/07.%20App%20Provider%20Management/01.%20Open%20API.md

@sachinargade123 also stated the following: "About callback request from app provider side was done and also we received the technical credentials and app id. we configured the same information for mentioned instances.", not certain how that fits into the picture.

Call for clarification happening in couple of hours.

**Comment by ntruchsess** [comment]
Issues identified:
* endpoint PUT /api/apps/subscription/{subscriptionId}/activate is expected be called by the app-provider-management serviceaccount that has 'activate_subscription' permission.
* the endpoint PUT /api/apps/subscription/{subscriptionId}/activate is incorrectly mapped to * endpoint PUT /subscription/{subscriptionId}/activate and therefore not accessible due to the ingress not being able to route without /api/apps prefix

**Comment by evegufy** [comment]
@sachinargade123 @ciprianherciu the activation is ready for retest

**Comment by evegufy** [comment]
https://github.com/eclipse-tractusx/portal-backend/pull/861 was tested successfully
but once the endpoint could be called the following was observed by @sachinargade123 

> After hit activate API when I checked the portal -> App subscription managed tab. The subscription status get changed from ‘TRIGGER_ACTIVATE_SUBSCRIPTION’ to ‘ACTIVATE_SUBSCRIPTION’ and, there activate button get enable PFA.  
> I just checked open the actual subscription URL and it work as expected(showing key cloak login page) but the actual subscription is not enabled/displaced in user management section for role and user assignment for subscription.

we were able to trace it back to the following error during activation:
```
clientId somedimclientid not found in central keycloak
```

So, the processes worker attempted to find the external clientId (from the DIM) in centralidp Keycloak, that can not work and @ntruchsess is providing a fix to only consider internal clientids.

**Comment by ntruchsess** [comment]
PR https://github.com/eclipse-tractusx/portal-backend/pull/864 is ready. It changes the relevant query to return only serviceAccounts that are CompanyServiceAccountKindId.INTERNAL

**Comment by evegufy** [comment]
After the fix from https://github.com/eclipse-tractusx/portal-backend/pull/864 the activation was now executed successfully.
We noticed still some issues in the process after the activation of the subscription, as the step “TRIGGER_PROVIDER_CALLBACK” is failing with the error “Callback Url should be set here” and @ntruchsess will take care of that.
But the information provided in this callback should be also available in the Portal interface, so you shouldn’t be blocked any longer from continuing with your tests.

**Comment by ntruchsess** [comment]
A fix for the TRIGGER_PROVIDER_CALLBACK-related error is implemented in PR https://github.com/eclipse-tractusx/portal-backend/pull/865

**Comment by evegufy** [comment]
The change for completing the process with callback is now merged as well https://github.com/eclipse-tractusx/portal-backend/pull/865, thanks @ntruchsess Could you please also complete the [appsettings.json ](https://github.com/eclipse-tractusx/portal-backend/blob/v2.1.0-RC1/src/processes/Processes.Worker/appsettings.json)for missing default values like the [clientPrefix available in the apps service](https://github.com/eclipse-tractusx/portal-backend/blob/v2.1.0-RC1/src/marketplace/Services.Service/appsettings.json#L77)? And please also raise a pull request to portal-assets to update the documentation where needed:
https://github.com/search?q=repo%3Aeclipse-tractusx%2Fportal-assets%20autosetup&type=code

Could you please also check if the autosetup for services is aligned with the recent bugfixes?
Related topic: I noticed a documentation error for the analog endpoint for services, it should be service instead of app:
![image](https://github.com/user-attachments/assets/44a14272-03ca-428d-babb-deaef1896137)

**Comment by evegufy** [comment]
I got confirmation that the process worked also E2E with a new subscription from @sachinargade123 and @ciprianherciu 
--> closing issue now.
I opened https://github.com/eclipse-tractusx/portal-assets/issues/374 to follow up on the documentation
